<?php

namespace srag\Plugins\AssessmentTest\ObjectSettings;

use ilAssessmentTestPlugin;
use ilCheckboxInputGUI;
use ilObjAssessmentTest;
use ilObjAssessmentTestGUI;
use ilTextAreaInputGUI;
use ilTextInputGUI;
use srag\CustomInputGUIs\AssessmentTest\PropertyFormGUI\Items\Items;
use srag\CustomInputGUIs\AssessmentTest\PropertyFormGUI\PropertyFormGUI;

/**
 * Class ObjectSettingsFormGUI
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AssessmentTest\ObjectSettings
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Core 2 <al@studer-raimann.ch>
 */
class ObjectSettingsFormGUI extends PropertyFormGUI
{

    const PLUGIN_CLASS_NAME = ilAssessmentTestPlugin::class;
    const LANG_MODULE = ilObjAssessmentTestGUI::LANG_MODULE_SETTINGS;
    /**
     * @var ilObjAssessmentTest
     */
    protected $object;


    /**
     * ObjectSettingsFormGUI constructor
     *
     * @param ilObjAssessmentTestGUI $parent
     * @param ilObjAssessmentTest    $object
     */
    public function __construct(ilObjAssessmentTestGUI $parent, ilObjAssessmentTest $object)
    {
        $this->object = $object;

        parent::__construct($parent, $object);
    }


    /**
     * @inheritDoc
     */
    protected function getValue(/*string*/ $key)
    {
        switch ($key) {
            case "description":
                return Items::getter($this->object, "long_description");

            default:
                return Items::getter($this->object, $key);
        }
    }


    /**
     * @inheritDoc
     */
    protected function initCommands()/*: void*/
    {
        $this->addCommandButton(ilObjAssessmentTestGUI::CMD_SETTINGS_STORE, self::plugin()->translate("save", self::LANG_MODULE));

        $this->addCommandButton(ilObjAssessmentTestGUI::CMD_MANAGE_CONTENTS, self::plugin()->translate("cancel", self::LANG_MODULE));
    }


    /**
     * @inheritDoc
     */
    protected function initFields()/*: void*/
    {
        $this->fields = [
            "title"       => [
                self::PROPERTY_CLASS    => ilTextInputGUI::class,
                self::PROPERTY_REQUIRED => true
            ],
            "description" => [
                self::PROPERTY_CLASS    => ilTextAreaInputGUI::class,
                self::PROPERTY_REQUIRED => false
            ],
            "online"      => [
                self::PROPERTY_CLASS => ilCheckboxInputGUI::class
            ]
        ];
    }


    /**
     * @inheritDoc
     */
    protected function initId()/*: void*/
    {

    }


    /**
     * @inheritDoc
     */
    protected function initTitle()/*: void*/
    {
        $this->setTitle(self::plugin()->translate("settings", self::LANG_MODULE));
    }


    /**
     * @inheritDoc
     */
    protected function storeValue(/*string*/ $key, $value)/*: void*/
    {
        switch ($key) {
            default:
                Items::setter($this->object, $key, $value);
                break;
        }
    }


    /**
     * @inheritDoc
     */
    public function storeForm() : bool
    {
        if (!parent::storeForm()) {
            return false;
        }

        $this->object->update();

        return true;
    }
}
