<?php

use ILIAS\Data\UUID\Factory;
use srag\asq\Test\Domain\Test\Modules\IQuestionSourceModule;
use srag\asq\Test\Leipzig\LeipzigTest;
use srag\asq\Test\Lib\Event\IEventUser;
use srag\asq\Test\Modules\Questions\QuestionPage;
use srag\DIC\AssessmentTest\DICTrait;
use srag\Plugins\AssessmentTest\Utils\AssessmentTestTrait;
use srag\asq\Application\Service\ASQDIC;
use srag\asq\Infrastructure\Persistence\QuestionType;
use srag\asq\Infrastructure\Setup\lang\SetupAsqLanguages;
use srag\asq\Infrastructure\Setup\sql\SetupDatabase;
use srag\asq\Test\AsqTestServices;
use srag\asq\Test\Application\TestRunner\TestRunnerService;
use srag\asq\Test\Domain\Result\Model\AssessmentResultContext;
use srag\asq\Test\Domain\Test\Model\AssessmentTestDto;
use srag\asq\Test\Infrastructure\Setup\lang\SetupAsqTestLanguages;
use srag\asq\Test\Infrastructure\Setup\sql\SetupAsqTestDatabase;
use srag\asq\Test\UI\ConfigurationGUI;
use srag\asq\Test\Domain\Test\Model\TestData;

/**
 * Class ilObjAssessmentTestGUI
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @author studer + raimann ag - Adrian Lüthi <al@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy ilObjAssessmentTestGUI: ilRepositoryGUI
 * @ilCtrl_isCalledBy ilObjAssessmentTestGUI: ilObjPluginDispatchGUI
 * @ilCtrl_isCalledBy ilObjAssessmentTestGUI: ilAdministrationGUI
 * @ilCtrl_Calls      ilObjAssessmentTestGUI: ilPermissionGUI
 * @ilCtrl_Calls      ilObjAssessmentTestGUI: ilInfoScreenGUI
 * @ilCtrl_Calls      ilObjAssessmentTestGUI: ilObjectCopyGUI
 * @ilCtrl_Calls      ilObjAssessmentTestGUI: ilCommonActionDispatcherGUI
 * @ilCtrl_Calls      ilObjAssessmentTestGUI: AsqQuestionAuthoringGUI
 * @ilCtrl_Calls      ilObjAssessmentTestGUI: TestPlayerGUI
 * @ilCtrl_Calls      ilObjAssessmentTestGUI: QuestionPoolSelectionGUI
 */
class ilObjAssessmentTestGUI extends ilObjectPluginGUI
{
    use DICTrait;
    use AssessmentTestTrait;
    const PLUGIN_CLASS_NAME = ilAssessmentTestPlugin::class;
    const CMD_SHOW_QUESTIONS = "showQuestions";
    const CMD_PERMISSIONS = "perm";
    const CMD_SETTINGS = "settings";
    const CMD_SHOW_CONTENTS = "showTest";
    const CMD_INIT_ASQ = "initASQ";
    const CMD_CLEAR_ASQ = "clearASQ";

    const LANG_MODULE_OBJECT = "object";
    const LANG_MODULE_SETTINGS = "settings";
    const TAB_CONTENTS = "contents";
    const TAB_PERMISSIONS = "perm_settings";
    const TAB_SETTINGS = "settings";
    const TAB_QUESTIONS = "questions";

    const COL_TITLE = 'QUESTION_TITLE';
    const COL_TYPE = 'QUESTION_TYPE';
    const COL_AUTHOR = 'QUESTION_AUTHOR';
    const COL_EDITLINK = "QUESTION_EDITLINK";
    const VAL_NO_TITLE = '-----';

    private AssessmentTestDto $test_data;

    private LeipzigTest $test;

    private Factory $uuid_factory;

    private AsqTestServices $asq_test;

    /**
     * @inheritDoc
     */
    protected function afterConstructor()/*: void*/
    {
        global $DIC;

        ASQDIC::initiateASQ($DIC);

        $this->uuid_factory = new Factory();
        $this->asq_test = AsqTestServices::get();

        $this->loadTest();
    }

    private function loadTest() : void
    {
        if ($this->object === null) {
            return;
        }

        $raw_test_id = $this->object->getData();

        if (is_null($raw_test_id)) {
            $this->createNewTest();
        }
        else {
            $this->test_data = $this->asq_test->test()->getTest(
                $this->uuid_factory->fromString($raw_test_id)
            );
        }

        $this->test = new LeipzigTest($this->test_data);
    }

    private function createNewTest() : void
    {
        $test_id = $this->asq_test->test()->createTest();
        $this->object->setData($test_id->toString());
        $this->object->doUpdate();

        $this->test_data = $this->asq_test->test()->getTest($test_id);
        $this->test_data->setTestData(new TestData($this->object->getTitle(), $this->object->getDescription()));
    }

    /**
     * @inheritDoc
     */
    final public function getType() : string
    {
        return ilAssessmentTestPlugin::PLUGIN_ID;
    }

    public function performCommand(string $cmd)/*: void*/
    {
        self::dic()->help()->setScreenIdComponent(ilAssessmentTestPlugin::PLUGIN_ID);

        $next_class = self::dic()->ctrl()->getNextClass($this);

        switch (strtolower($next_class)) {
            case strtolower(TestPlayerGUI::class):
                self::dic()->tabs()->activateTab(self::TAB_CONTENTS);
                self::dic()->ctrl()->forwardCommand(new TestPlayerGUI());
                return;
            default:
                switch ($cmd) {
                    case self::CMD_SHOW_CONTENTS:
                    case self::CMD_SHOW_QUESTIONS:
                    case self::CMD_SETTINGS:
                    case self::CMD_INIT_ASQ:
                    case self::CMD_CLEAR_ASQ:
                        // Write commands
                        if (!ilObjAssessmentTestAccess::hasWriteAccess()) {
                            ilObjAssessmentTestAccess::redirectNonAccess($this);
                        }

                        $this->{$cmd}();
                        break;

                    default:
                        $this->test->executeCommand($cmd);
                        $this->show();
                        break;
                }
                break;
        }
    }

    /**
     * @param string $html
     */
    protected function show()/*: void*/
    {
        foreach ($this->test->ui()->getTabs() as $tab) {
            self::dic()->tabs()->addTab(
                $tab->getId(),
                $tab->getText(),
                self::dic()->ctrl()->getLinkTarget($this, $tab->getLink())
            );

            if($tab->isActive()) {
                self::dic()->tabs()->activateTab($tab->getId());
            }
        }

        foreach ($this->test->ui()->getToolbar() as $tool) {
            self::dic()->toolbar()->addComponent($tool);
        }

        self::dic()->ui()->mainTemplate()->setTitle($this->test->ui()->getTitle());

        self::dic()->ui()->mainTemplate()->setDescription($this->test->ui()->getDescription());

        self::output()->output($this->test->ui()->getContent());
    }


    /**
     * @inheritDoc
     */
    public function initCreateForm(/*string*/ $a_new_type) : ilPropertyFormGUI
    {
        $form = parent::initCreateForm($a_new_type);

        return $form;
    }


    /**
     * @inheritDoc
     *
     * @param ilObjAssessmentTest $a_new_object
     */
    public function afterSave(/*ilObjAssessmentTest*/ ilObject $a_new_object)/*: void*/
    {
        parent::afterSave($a_new_object);
    }


    /**
     *
     */
    protected function showTest()/*: void*/
    {
        $srv = new TestRunnerService();

        $context_uid = $srv->createTestRun(
            new AssessmentResultContext(self::dic()->user()->getId(), 'testrun'),
            array_map(function ($question) {
                return $question->getId();
            }, $this->section->getItems())
        );

        self::dic()->ctrl()->setParameterByClass(TestPlayerGUI::class, TestPlayerGUI::PARAM_CURRENT_RESULT, $context_uid->toString());
        self::dic()->ctrl()->redirectToURL(
            self::dic()->ctrl()->getLinkTargetByClass(TestPlayerGUI::class, TestPlayerGUI::CMD_RUN_TEST, "", false, false)
        );
    }


    /**
     *
     */
    protected function showQuestions()/*: void*/
    {
        global $ASQDIC;

        self::dic()->tabs()->activateTab(self::TAB_QUESTIONS);

        $button = ilLinkButton::getInstance();
        $button->setUrl(self::dic()->ctrl()->getLinkTargetByClass(self::class, self::CMD_INIT_ASQ));
        $button->setCaption("Init ASQ", false);
        self::dic()->toolbar()->addButtonInstance($button);

        $button = ilLinkButton::getInstance();
        $button->setUrl(self::dic()->ctrl()->getLinkTargetByClass(self::class, self::CMD_CLEAR_ASQ));
        $button->setCaption("Clear ASQ", false);
        self::dic()->toolbar()->addButtonInstance($button);

        $question_table = new ilTable2GUI($this);
        $question_table->setRowTemplate("tpl.questions_row.html", "Customizing/global/plugins/Services/Repository/RepositoryObject/AssessmentTest");
        $question_table->addColumn(self::plugin()->translate("header_title"), self::COL_TITLE);
        $question_table->addColumn(self::plugin()->translate("header_type"), self::COL_TYPE);
        $question_table->addColumn(self::plugin()->translate("header_creator"), self::COL_AUTHOR);

        $question_table->setData($this->getQuestionsOfContainerAsAssocArray());

        $this->show($question_table->getHTML());
    }

    private function getQuestionsOfContainerAsAssocArray() : array
    {
        return [];
        global $ASQDIC;

        $assoc_array = [];

        $items = $this->section->getItems();

        if (is_null($items)) {
            return $assoc_array;
        }

        foreach ($items as $item) {
            $question_dto = $ASQDIC->asq()->question()->getQuestionByQuestionId($item->getId());

            $data = $question_dto->getData();

            $question_array[self::COL_TITLE] = is_null($data) ? self::VAL_NO_TITLE : (empty($data->getTitle()) ? self::VAL_NO_TITLE : $data->getTitle());
            $question_array[self::COL_TYPE] = self::dic()->language()->txt($question_dto->getType()->getTitleKey());
            $question_array[self::COL_AUTHOR] = is_null($data) ? '' : $data->getAuthor();
            $question_array[self::COL_EDITLINK] = $ASQDIC->asq()->link()->getEditLink($question_dto->getId())->getAction();

            $assoc_array[] = $question_array;
        }

        return $assoc_array;
    }

    protected function initASQ()
    {
        QuestionType::resetDB();
        SetupDatabase::new()->run();
        SetupAsqLanguages::new()->run();
        SetupAsqTestDatabase::run();
        SetupAsqTestLanguages::new()->run();

        $this->showQuestions();
    }

    protected function clearASQ()
    {
        global $DIC;

        //resetup asq for question types
        SetupDatabase::new()->uninstall();
        SetupDatabase::new()->run();
        SetupAsqLanguages::new()->run();

        foreach($this->section->getItems() as $item) {
            $this->asq_test->removeQuestion($this->section->getId(), $item->getId());
        }

        $DIC->ctrl()->redirectToURL($DIC->ctrl()->getLinkTarget($this, self::CMD_SHOW_QUESTIONS, "", false, false));
    }

    /**
     *
     */
    protected function settings()/*: void*/
    {

        self::dic()->tabs()->activateTab(self::TAB_SETTINGS);

        $form = new ConfigurationGUI($this->test_data);

        $subtabs = $form->getSubTabs();
        foreach ($subtabs as $key => $value) {
            self::dic()->ctrl()->setParameter($this, ConfigurationGUI::CURRENT_CONFIG, $key);
            self::dic()->tabs()->addSubTab(
                 $key,
                 $value,
                 self::dic()->ctrl()->getLinkTarget($this, self::CMD_SETTINGS));
        }

        $current_subtab = $_GET[ConfigurationGUI::CURRENT_CONFIG] ?? array_key_first($subtabs);
        if ($current_subtab !== null) {
            self::dic()->tabs()->activateSubTab($current_subtab);
        }

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $this->test_data = $form->getEditedTest();
            $this->asq_test->test()->saveTest($this->test_data);
        }

        self::output()->output($form->render($current_subtab));
    }

    /**
     *
     */
    protected function setTabs()/*: void*/
    {
        return;

        self::dic()->tabs()->addTab(self::TAB_CONTENTS, self::plugin()->translate("show_contents", self::LANG_MODULE_OBJECT), self::dic()->ctrl()
            ->getLinkTarget($this, self::CMD_SHOW_CONTENTS));

        if (ilObjAssessmentTestAccess::hasWriteAccess()) {
            self::dic()->tabs()->addTab(self::TAB_QUESTIONS, self::plugin()->translate("questions", self::LANG_MODULE_OBJECT), self::dic()
                ->ctrl()->getLinkTarget($this, self::CMD_SHOW_QUESTIONS));

            self::dic()->tabs()->addTab(self::TAB_SETTINGS, self::plugin()->translate("settings", self::LANG_MODULE_SETTINGS), self::dic()->ctrl()
                ->getLinkTarget($this, self::CMD_SETTINGS));
        }

        if (ilObjAssessmentTestAccess::hasEditPermissionAccess()) {
            self::dic()->tabs()->addTab(self::TAB_PERMISSIONS, self::plugin()->translate(self::TAB_PERMISSIONS, "", [], false), self::dic()->ctrl()
                ->getLinkTargetByClass([
                    self::class,
                    ilPermissionGUI::class
                ], self::CMD_PERMISSIONS));
        }

        self::dic()->tabs()->manual_activation = true; // Show all tabs as links when no activation
    }


    /**
     * @return string
     */
    public static function getStartCmd() : string
    {
        if (ilObjAssessmentTestAccess::hasWriteAccess()) {
            return QuestionPage::SHOW_QUESTIONS;
        } else {
            return self::CMD_SHOW_CONTENTS;
        }
    }


    /**
     * @inheritDoc
     */
    public function getAfterCreationCmd() : string
    {
        return self::getStartCmd();
    }


    /**
     * @inheritDoc
     */
    public function getStandardCmd() : string
    {
        return self::getStartCmd();
    }
}
