<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\AssessmentTest\Utils\AssessmentTestTrait;
use srag\RemovePluginDataConfirm\AssessmentTest\RepositoryObjectPluginUninstallTrait;
use srag\asq\Infrastructure\Setup\lang\SetupAsqLanguages;
use srag\asq\Infrastructure\Setup\sql\SetupDatabase;
use srag\asq\Test\Infrastructure\Setup\lang\SetupAsqTestLanguages;
use srag\asq\Test\Infrastructure\Setup\sql\SetupAsqTestDatabase;

/**
 * Class ilAssessmentTestPlugin
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Core 2 <al@studer-raimann.ch>
 */
class ilAssessmentTestPlugin extends ilRepositoryObjectPlugin
{

    use RepositoryObjectPluginUninstallTrait;
    use AssessmentTestTrait;
    const PLUGIN_ID = "xast";
    const PLUGIN_NAME = "AssessmentTest";
    const PLUGIN_CLASS_NAME = self::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * ilAssessmentTestPlugin constructor
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * @inheritDoc
     */
    public function getPluginName() : string
    {
        return self::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function updateLanguages(/*?array*/ $a_lang_keys = null)/*:void*/
    {
        parent::updateLanguages($a_lang_keys);

        $this->installRemovePluginDataConfirmLanguages();
    }


    /**
     * @inheritDoc
     */
    protected function deleteData()/*: void*/
    {
        self::assessmentTest()->dropTables();
    }
    
    /**
     * @inheritDoc
     */
    protected function afterActivation() {
        SetupDatabase::new()->run();
        SetupAsqTestDatabase::run();
        SetupAsqLanguages::new()->run();
        SetupAsqTestLanguages::new()->run();
    }
}
