<?php

namespace srag\Plugins\AssessmentTest\Config;

use ilAssessmentTestConfigGUI;
use ilAssessmentTestPlugin;
use ilTextInputGUI;
use srag\CustomInputGUIs\AssessmentTest\PropertyFormGUI\PropertyFormGUI;
use srag\Plugins\AssessmentTest\Utils\AssessmentTestTrait;

/**
 * Class ConfigFormGUI
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AssessmentTest\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Core 2 <al@studer-raimann.ch>
 */
class ConfigFormGUI extends PropertyFormGUI
{
    use AssessmentTestTrait;
    const PLUGIN_CLASS_NAME = ilAssessmentTestPlugin::class;
    const KEY_SOME = "some";
    const LANG_MODULE = ilAssessmentTestConfigGUI::LANG_MODULE;


    /**
     * ConfigFormGUI constructor
     *
     * @param ilAssessmentTestConfigGUI $parent
     */
    public function __construct(ilAssessmentTestConfigGUI $parent)
    {
        parent::__construct($parent);
    }


    /**
     * @inheritDoc
     */
    protected function getValue(/*string*/ $key)
    {
        switch ($key) {
            default:
                return self::assessmentTest()->config()->getValue($key);
        }
    }


    /**
     * @inheritDoc
     */
    protected function initCommands()/*: void*/
    {
        $this->addCommandButton(ilAssessmentTestConfigGUI::CMD_UPDATE_CONFIGURE, $this->txt("save"));
    }


    /**
     * @inheritDoc
     */
    protected function initFields()/*: void*/
    {
        $this->fields = [
            self::KEY_SOME => [
                self::PROPERTY_CLASS => ilTextInputGUI::class,
                self::PROPERTY_REQUIRED => true
            ]
        ];
        // TODO: Implement ConfigFormGUI
    }


    /**
     * @inheritDoc
     */
    protected function initId()/*: void*/
    {
    }


    /**
     * @inheritDoc
     */
    protected function initTitle()/*: void*/
    {
        $this->setTitle($this->txt("configuration"));
    }


    /**
     * @inheritDoc
     */
    protected function storeValue(/*string*/ $key, $value)/*: void*/
    {
        switch ($key) {
            default:
                self::assessmentTest()->config()->setValue($key, $value);
                break;
        }
    }
}
