<?php

namespace srag\Plugins\AssessmentTest\Config;

use srag\Plugins\AssessmentTest\Utils\AssessmentTestTrait;
use ilAssessmentTestPlugin;
use srag\ActiveRecordConfig\AssessmentTest\Config\AbstractFactory;
use srag\ActiveRecordConfig\AssessmentTest\Config\AbstractRepository;
use srag\ActiveRecordConfig\AssessmentTest\Config\Config;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AssessmentTest\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Core 2 <al@studer-raimann.ch>
 */
final class Repository extends AbstractRepository
{

    use AssessmentTestTrait;
    const PLUGIN_CLASS_NAME = ilAssessmentTestPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * Repository constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @inheritDoc
     *
     * @return Factory
     */
    public function factory() : AbstractFactory
    {
        return Factory::getInstance();
    }


    /**
     * @inheritDoc
     */
    protected function getTableName() : string
    {
        return ilAssessmentTestPlugin::PLUGIN_ID . "_config";
    }


    /**
     * @inheritDoc
     */
    protected function getFields() : array
    {
        return [
            ConfigFormGUI::KEY_SOME => Config::TYPE_STRING
        ];
    }
}
