<?php

namespace srag\Plugins\AssessmentTest\Utils;

use srag\Plugins\AssessmentTest\Repository;

/**
 * Trait AssessmentTestTrait
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AssessmentTest\Utils
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Core 2 <al@studer-raimann.ch>
 */
trait AssessmentTestTrait
{

    /**
     * @return Repository
     */
    protected static function assessmentTest() : Repository
    {
        return Repository::getInstance();
    }
}
